import { TeamMember } from "./team.types";

export const TEAM: TeamMember[] = [
  {
    id: "exec-1",
    name: "Ayesha Rahman",
    role: "President",
    dept: "Executive",
    headshot: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=800&auto=format&fit=crop",
    bio: "Leads strategy, culture nights, and partnerships. Loves Tagore and biryani.",
    email: "ayesha@utsbdsoc.org",
    instagram: "https://instagram.com/",
    linkedin: "https://www.linkedin.com/",
    order: 1,
  },
  {
    id: "exec-2",
    name: "Zayan Ahmed",
    role: "Vice President",
    dept: "Executive",
    headshot: "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?q=80&w=800&auto=format&fit=crop",
    bio: "Logistics lead and sports tragic. Organises Sports Day and futsal nights.",
    email: "zayan@utsbdsoc.org",
    linkedin: "https://www.linkedin.com/",
    order: 2,
  },
  {
    id: "exec-3",
    name: "Nabila Chowdhury",
    role: "Secretary",
    dept: "Executive",
    headshot: "https://images.unsplash.com/photo-1556157382-97eda2d62296?q=80&w=800&auto=format&fit=crop",
    bio: "Keeps the lights on: minutes, budget, and venue bookings.",
    email: "nabila@utsbdsoc.org",
    instagram: "https://instagram.com/",
    order: 3,
  },
  {
    id: "events-1",
    name: "Rafi Khan",
    role: "Events Director",
    dept: "Events",
    headshot: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=800&auto=format&fit=crop",
    bio: "Programs our cultural nights and mixers. Loves a good countdown timer.",
    instagram: "https://instagram.com/",
  },
  {
    id: "events-2",
    name: "Maliha Noor",
    role: "Events Coordinator",
    dept: "Events",
    headshot: "https://images.unsplash.com/photo-1546967191-fdfb13ed6b1e?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "media-1",
    name: "Sameer Ali",
    role: "Media Director",
    dept: "Media",
    headshot: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?q=80&w=800&auto=format&fit=crop",
    bio: "Edits reels, shoots photo/video, and runs the IG playbook.",
    instagram: "https://instagram.com/",
    linkedin: "https://www.linkedin.com/",
  },
  {
    id: "media-2",
    name: "Nusrat Jahan",
    role: "Designer",
    dept: "Media",
    headshot: "https://images.unsplash.com/photo-1544717305-2782549b5136?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "spons-1",
    name: "Tahmid Islam",
    role: "Sponsorship Lead",
    dept: "Sponsorship",
    headshot: "https://images.unsplash.com/photo-1544006659-f0b21884ce1d?q=80&w=800&auto=format&fit=crop",
    linkedin: "https://www.linkedin.com/",
  },
  {
    id: "sports-1",
    name: "Priya Das",
    role: "Sports Coordinator",
    dept: "Sports",
    headshot: "https://images.unsplash.com/photo-1544005316-04d4ac99d87b?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "tech-1",
    name: "Imran Hossain",
    role: "Tech Lead",
    dept: "Tech",
    headshot: "https://images.unsplash.com/photo-1556157381-97eda2d62296?q=80&w=800&auto=format&fit=crop",
    email: "imran@utsbdsoc.org",
    linkedin: "https://www.linkedin.com/",
  },
  {
    id: "community-1",
    name: "Sara N.",
    role: "Community Manager",
    dept: "Community",
    headshot: "https://images.unsplash.com/photo-1544005313-1b30f5d1b816?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "events-3",
    name: "Arif Bin",
    role: "Stage Manager",
    dept: "Events",
    headshot: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=800&auto=format&fit=crop",
  },
];
